### ISSUE TITLE
Issue with BorderRadius?

### ISSUE THREAD

**Issue by seb-giroux** [SuavePirate/MaterialButton#1]
Hi there,

I've set the `BorderRadius` of the `MaterialButton` to half the width (in order to get the famous material circular button), but the shadow does not reflect the button anymore.

i.e. if it's not meant to be a Floating action button, I understand as well. :)

**Comment by SuavePirate** [comment]
This isn't really meant to be a FAB - I have another control for that here https://github.com/SuavePirate/Xamarin.Forms.Controls.FloatingActionButton 

This handles the shadows and everything else for you on iOS to get a better FAB look and feel (and uses the native FAB control on Android)
